version: '2'
services:

  backend:
    image: $IMAGE_DEV
    container_name: $CONTAINER_NAME
    volumes:
      - ./app/:/app
      - ~/.ssh:/root/.ssh
      - ~/.aws/:/root/.aws/
    environment:
      DEPLOY_REGION: $DEPLOY_REGION
      LC_ALL: en_US.UTF-8
      TZ: America/Lima
    ports:
      - 80:80

  mysql56:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_project
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
